### PR TITLE
Adds opentracing support

### PR DESCRIPTION
**Pull request by elgris**
According to agreed Zalando standards

### CODE REVIEW

**Comment by vetinari** [comment]
:+1:

**Comment by mohabusama** [comment]
What does it mean? `According to agreed Zalando standards`

**Comment by elgris** [comment]
@mohabusama well, actually, according to ZMON standards :)
1. having `opentracing-spring-cloud-starter` as a dependency
2. not using any particular tracer by default

**Comment by elgris** [comment]
👍

**Pull request merged**
